### ISSUE TITLE
"str error 10"

### ISSUE THREAD

**Issue by luoxin1992** [nanopool/Claymore-Dual-Miner#180] opened 2018-01-08 09:31 UTC
when I execute "/path/to/claymore/ethdcrminer64" with some parameters, I get a stdout look like "str error 10". That's because the parameters I given are not correct, or what other reasons? My OS is ubuntu 16.04.3.

**Comment by Suntechnic** [comment] 2018-01-17 20:28
I get the same error.
Linux alex-desktop 4.13.0-26-generic #29~16.04.2-Ubuntu SMP Tue Jan 9 22:00:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

/opt/miner/claymore/ethdcrminer64 -epool eth.2miners.ru:2020 -eworker str1 -ewal 0afa5822ae8ef88ae436eda5c78e01c7d2743d41 -epsw x

**Comment by gvjtownsend** [comment] 2018-01-27 18:25
Me too!!! ... and I've been using claymore for several months now, but today I set up a new ubuntu 16.04.3 mining rig, and all of a sudden I've got this too. I even tried tar-ing up a copy of all the stuff I use from a working rig and untar'ed it on the new rig, but I still get this "str error 10" for no good reason.  :(
-gt-

**Comment by deepybee** [comment] 2018-02-09 09:53
I get the same error on Ubuntu 16.04.3 with 1 x AMD RX480 8GB, 1 x Nvidia GTX 1060 3GB and 1 x Nvidia GTX 780 3GB. Looks like this is an incompatibility with this release of Ubuntu as this miner was working without issue on Arch Linux before I rebuilt the rig to run under Ubuntu (to leverage the `amdgpu-pro` kernel module properly for maximum hashrate from the RX480 which isn't supported in Arch and so is pretty flaky at best).

Have switched to ethminer which is working on the rebuilt rig without issue. Hopefully this miner can be fixed for Ubuntu rigs soon.

**Comment by gvjtownsend** [comment] 2018-02-12 23:57
Here's a new twist ... one of my rigs has been operating fine for weeks using various GTX1050ti cards. I've been booting, rebooting, switching cards around trying different brands, etc. etc. without any problems. Then today a GTX960 arrived in the mail and I dropped it into this rig, and go this dreaded "str error 10" for the first time. I pulled the card, put everything back to normal, and now I can't get rid of this error. I made absolutely no changes when I dropped the card in, so whatever happened, happened automatically. I've tried reinstalling my NVIDIA drivers and Cuda, and nothing I do will make this error go away. So what happened? Why did the temporary presence of the new GTX960 wreck my mining rig?
-gt-

**Comment by rdavis852** [comment] 2018-02-13 01:13
Don't know if it will help but I'd remove all but the primary video card.... Get it to work and add the rest in one at a time.    This gives the mother board a chance to assign PCI-E slots and the operating system a chance to apply resources.

**Comment by gvjtownsend** [comment] 2018-02-13 02:52
?Yeah, I tried stripping it back down and incrementally adding cards, but it didn't help. I monkeyed with it all evening and have arrived at the point where I'm just preparing to reinstall Ubuntu. I wish I knew what installing that GPU did so I could undo it instead, but in the end I guess a reinstall is my quickest fix.

-gt-


________________________________

**Comment by Stemulite** [comment] 2018-02-13 18:15
Dam, I just got it last night after modifying my .sh file in an attempt to stop the ridiculous log files from clogging up all resources but now I can't get rid of it. I am back working on it today and will report if I find anything but until then my rig is down, really sucks.

**Comment by Stemulite** [comment] 2018-02-13 18:18
gvjtownsend , did you just reboot from a thumb drive? I have one and tried to use it last night but was taking forever booting so I aborted.....Any help greatly appreciated!

**Comment by gvjtownsend** [comment] 2018-02-13 18:27
?Yeah, I reinstalled from an Ubuntu installation thumb drive. Sadly, now something else has gone wrong and my rig won't recognize any GPUs. I guess that's unrelated to the "str error 10" problem, but basically, I'm stuck now until I sort that out.  I had been running my GPUs off the motherboard on risers. Now I can't even get past the BIOS check even if I plug a GPU right into the motherboard. Obviously a new unrelated problem.

-gt-


________________________________

**Comment by Stemulite** [comment] 2018-02-13 18:36
Just received this from 2miner support:

We recommend you to ask this question to pro-miners in our Telegram or Slack support chats:
https://t.me/chat2miners
https://join.slack.com/t/2miners/shared_invite/enQtMjkyMDc2MzI2MTI5LThhZjAxNzQwNGUyZWYwNTZiNjUyM2JiOTIyNTAxODMzMjg3MjYzZGUyNWU2NWFhNGRkZjgwZGE0MzFiNDgzZmE
Probably some of them have already solved this question and could share the solution with you.

Thanks for writing to us,
2Miners Support Team

**Comment by gvjtownsend** [comment] 2018-02-14 11:49
Okay, I solved my problem completely now. I had made a tar file of my entire claymore directory AFTER my initial "str error 10" and I restored it after each attempt at a rebuild. After spinning my wheels for days, I realized that I had deleted a mess of files in my claymore folder all named "Data???.bin" and I did not discover this until late last night. Originally I had thought those files were something I created myself when debugging, but when I examined the source files for claymore on github, I spotted them in the original zip of claymore. I snagged them from one of my working rigs and copied them over to this problematic rig, and suddenly my "str error 10" error vanished and my rig started mining up a storm.

**Comment by Stemulite** [comment] 2018-02-14 11:55
Thats great and you know what, that is exactly what I did. Deleted those files because I was just trying to clean up. I am at the point where I may have gone too far with different directory's and changing .sh files. I have no idea how to clean up now. I have made no back ups on my rig whatsoever.
What do you think is my best move? Glad you are back up and running!

**Comment by gvjtownsend** [comment] 2018-02-14 12:55
Well, if it helps, here's what I've got in my claymore directory after the dust has settled:

total 51392
-rwxrwxr-x  1 gt   gt        132 Nov  9  2016 config.txt
-rwxrwxr-x  1 gt   gt      67248 Dec 22  2016 ethdcrminer64
-rwxrwxr-x  1 gt   gt       1286 Feb 23  2017 License.txt
-rwxrwxr-x  1 gt   gt        401 May 12  2017 start_eth+pasc.bash
-rwxrwxr-x  1 gt   gt        279 May 12  2017 start_only_eth.bash
-rwxrwxr-x  1 gt   gt      21463 Sep  1 08:18 History.txt
-rwxrwxr-x  1 gt   gt        811 Nov 17 15:24 dpools.txt
-rwxrwxr-x  1 gt   gt        621 Nov 17 15:25 epools.txt
-rwxrwxr-x  1 gt   gt      38996 Dec  1 20:44 Readme!!!.txt
-rwxrwxr-x  1 gt   gt        523 Dec  1 20:47 start.bash
-rwxrwxr-x  1 gt   gt      23482 Feb 13 23:39 Data1a1.bin
-rwxrwxr-x  1 gt   gt      23902 Feb 13 23:39 Data1b1.bin
-rwxrwxr-x  1 gt   gt      23511 Feb 13 23:39 Data1d1.bin
-rwxrwxr-x  1 gt   gt      23516 Feb 13 23:39 Data1c1.bin
-rwxrwxr-x  1 gt   gt      23838 Feb 13 23:39 Data1e1.bin
-rwxrwxr-x  1 gt   gt      23838 Feb 13 23:39 Data1e2.bin
-rwxrwxr-x  1 gt   gt      23589 Feb 13 23:39 Data1g1.bin
-rwxrwxr-x  1 gt   gt      23584 Feb 13 23:39 Data1h1.bin
-rwxrwxr-x  1 gt   gt      23589 Feb 13 23:39 Data1g2.bin
-rwxrwxr-x  1 gt   gt      55892 Feb 13 23:39 Data1i1.bin
-rwxrwxr-x  1 gt   gt     667440 Feb 13 23:39 Data3.bin
-rwxrwxr-x  1 gt   gt     765624 Feb 13 23:39 Data.bin
drwxrwxr-x  2 gt   gt       4096 Feb 14 07:42 .
drwxr-xr-x 20 gt   gt       4096 Feb 14 07:53 ..
~

?


________________________________

**Comment by Stemulite** [comment] 2018-02-14 20:17
Hey GTown, Thanks for the effort brother, not the exact files I wiped but close. Hey, did you consider just wiping everything out and starting over fresh? That is what I am considering here today.

**Comment by gvjtownsend** [comment] 2018-02-14 21:47
?Well the thing is I THOUGHT my tar file was from a clean install - I didn't realize that I'd wiped some important files, so each time I started fresh, I installed that same-old-tar file for claymore. Anyway, let me know how things go on your end - I hope you can get things sorted out too!

-gt-


________________________________

**Comment by Stemulite** [comment] 2018-02-16 00:49
Hey GTown, is your miner continuing to copy those logs? This was the only reason that I deleted any files. The entire system was bogged down filled up with useless lines of mining history. Why anyone would need this is beyond me. Curious to hear if this is still occurring for you since you fixed it. I am still out of commission with absolutely no clue short of bashing the whole system up with a baseball bat.

**Comment by gvjtownsend** [comment] 2018-02-16 04:40
?It still makes the logs named ???????????_log.txt, and its okay to scrub them of course. I find its useful if/when something goes wrong because you can find some clue in the logs, but mostly I just scrub them off once in a while. Those other things named Data?????.bin aren't logs and apparently need to be there for etherminer to work.

________________________________

**Comment by Stemulite** [comment] 2018-02-16 21:07
I wonder if I should just do a new download and re-install of claymore?

**Comment by boltronics** [comment] 2018-02-16 23:26
I got that error on my GNU/Linux install. Permissions included in the tarball for `Data3.bin` are `-rwx--xr--` for some reason, but all other files are -rw-r--r-- except `ethdcrminer64` which is rightly `-rwxr-xr-x`. This is the root cause of the issue for me - it's a packaging issue.

I restrict permissions on the app by running `chown -R root:claymore /path/to/claymore/root/dir` and having `ethdcrminer64` execute as a user that's a member of the `claymore` group. Because of the packaging permission issue (included within the tarball of the last few releases at least), this effectively blocked read access to `Data3.bin`.

If this is how you too hit the confusing `str error 10` error message, this is the work-around until the problem gets addressed in future releases:
`sudo chmod 0644 Data3.bin`

**Comment by Stemulite** [comment] 2018-02-16 23:58
So open terminal in the claymore dir then type this command?

**Comment by Stemulite** [comment] 2018-02-17 00:05
I am looking for someone to ssh in to take a look. I am total newbie and am afraid I may have gone too far here for my limited understanding. I am spending night and day attempting figure out and am afraid I am just making it worse. I tried HIVE OS, used a linux/ubuntu thumb drive to see for repair twice and was just stuck at "booting" for over an hour so did the old pull the plug abort routine. tried to download bleachbit, said not successful but will fire and I can't tell how to use that. System declines any kind of download, says "device is full".....Where is my baseball bat!

**Comment by gvjtownsend** [comment] 2018-02-17 00:30
?I'm not your best bet, but I'm willing to ssh in to help if no one else offers first. Wait and see who pops up out of the woodwork, and if no one else offers, let me know and I'll see if I can help.

-gt-

________________________________

**Comment by boltronics** [comment] 2018-02-17 03:36
> So open terminal in the claymore dir then type this command?

That should do it.

**Comment by Stemulite** [comment] 2018-02-17 07:19
Okay Tried that, kicked back "no such file or directory".....

**Comment by Stemulite** [comment] 2018-02-17 07:21
Gtown, thanks Man, I might just take you up on it if you don't mind taking a look....

**Comment by boltronics** [comment] 2018-02-17 07:28
@Stemulite Sounds like that's your problem - you're either missing the Data3.bin file (and maybe others?), or it was renamed to something else. Do make sure the case is correct! Compare against the list above. If Claymore cannot find that file, it's the same as if you have the permission issue I was running into - it cannot be read and you'll get `str error 10`.

If it does exist, the only other explanation I can think of is that you ran the command from the wrong directory. Presumably @gvjtownsend will be able to figure it out with shell access if you're still not getting anywhere.

**Comment by Stemulite** [comment] 2018-02-17 08:01
Thanks Bolt, was very specific on case and I am nearly sure this is one of the files I deleted. How can I be sure? I am looking for Data3.bin now....

**Comment by Stemulite** [comment] 2018-02-17 08:18
Cannot find the Data3.bin anywhere on the computer searching via gui. I am in the /usr/local/claymore10.2/ directory and there are no bin files here at all.....

**Comment by boltronics** [comment] 2018-02-17 13:49
In that case, you'll need to re-download the tarball and reinstall them. It's certainly not going to work without them. :wink:

Forums or a mailing list for your distro or something would be a better place to get support, since your issue no longer seems related to a bug in Claymore.

**Comment by Stemulite** [comment] 2018-02-17 15:14
I have now discovered that my dev/sda2 is 100% full. This must be why I get the "No room on device" messages when trying to down load

**Comment by deepybee** [comment] 2018-02-23 14:16
Props to @gvjtownsend - I'd copied the `ethdcrminer64` binary into `/bin` so it would be in `$PATH` - running it from the unpacked tarball directory fixed the issue.

**Comment by luoxin1992** [comment] 2018-02-27 05:33
A bit surprise for so many discussions, and sorry for I don't pay close attention to it. 
It seems that the reason for `str error 10` is not unique. For me, it's just because I create a soft link to `ethdcrminer64` in order to quick access it... It works fine when I execute it directly.
Although that sounds ridiculous, maybe as everyone said, there are some bugs in path access, file system permissions, even the compatibility for GPU/OS.

**Comment by boltronics** [comment] 2018-02-27 07:49
@luoxin1992 If the soft link is in a different directory where you intend to call it from, that surely won't work for the same reason - you're still making those files unavailable to the application since they are all searched for relative to the call to `ethdcrminer64`.

This is why you see lots of scripts like `/usr/bin/gajim` that do things like:
```
#!/bin/sh
# <GPL3 license, some ${UID} tests, etc.>
cd "/usr/share/gajim/src"
exec "/usr/bin/python" -OO $APP.py "$@"
```

From everything I've seen, I know there is a permission issue with the tarball (which only causes a problem in some environments), an unhelpful error message whenever the data files cannot be accessed (which may be triggered by anything from the permission issue to human error), and all other reports here seem to be human error (or human misunderstanding of how *NIX systems work). :wink: 

Certainly the developer could take some simple steps to avoid a lot of this confusion. Aside from getting permissions correct in future releases, this could be "solved" by having error messages that say helpful things like "Data file not found" or "Permission issue accessing data file". That would probably be enough to make this a non-issue.

**Closed** 2018-03-09 03:10 UTC
